name         'camptocamp-java'
version      '0.0.1'
source       'https://github.com/camptocamp/puppet-java'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp Java Module'
description  'Java Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-java'
